// Per-character spritesheet + animation configuration.
//
// All processed strips are uniform 220x220 horizontal frames generated by
// scripts/preprocess-sprites.cjs from the magenta reference sheets. Frame counts
// come from that script's output. The source art is a set of varied poses (not
// directional walk cycles), so directional movement is handled in the scene by
// horizontally flipping the sprite; the animations below cycle the available
// poses to keep characters lively.

export interface AnimDef {
  /** suffix; full key becomes `${charKey}-${name}` */
  name: string;
  frames: number[];
  frameRate: number;
  repeat: number; // -1 = loop
}

export interface CharSprite {
  key: string;
  file: string; // under /public
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  anims: AnimDef[];
}

const FW = 220;
const FH = 220;

// The source art is a set of varied poses (different sizes/positions within
// each 220px frame), so cycling frames makes a character appear to grow/shrink.
// We therefore keep every character on a single consistent frame and convey
// life through movement (player bob, NPC wander) instead of frame swaps.
function npcAnims(): AnimDef[] {
  return [{ name: "idle", frames: [0], frameRate: 1, repeat: -1 }];
}

export const SPRITES: Record<string, CharSprite> = {
  // Player. 6 poses: 0 sit/idle, 1-2 step, 3 dash, 4 sit-alt, 5 pounce.
  siggy: {
    key: "siggy",
    file: "characters/siggy.png",
    frameWidth: FW,
    frameHeight: FH,
    frameCount: 6,
    anims: [
      // single idle frame so the cat doesn't appear to change size between poses
      { name: "idle", frames: [0], frameRate: 1, repeat: -1 },
      { name: "walk", frames: [1, 2, 3], frameRate: 8, repeat: -1 },
      { name: "run", frames: [1, 2, 3], frameRate: 13, repeat: -1 },
      { name: "interact", frames: [5], frameRate: 6, repeat: 0 },
      { name: "celebrate", frames: [4, 5], frameRate: 6, repeat: 3 },
      { name: "sit", frames: [0], frameRate: 1, repeat: 0 },
    ],
  },
  seesac: { key: "seesac", file: "characters/seesac.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  siggy_anime: { key: "siggy_anime", file: "characters/siggy_anime.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  decka: { key: "decka", file: "characters/decka.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  nxr: { key: "nxr", file: "characters/nxr.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  rikky: { key: "rikky", file: "characters/rikky.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  rizan: { key: "rizan", file: "characters/rizan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  jez: { key: "jez", file: "characters/jez.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  stefan: { key: "stefan", file: "characters/stefan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  josh: { key: "josh", file: "characters/josh.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  evo: { key: "evo", file: "characters/evo.png", frameWidth: FW, frameHeight: FH, frameCount: 6, anims: npcAnims() },
  asceno: { key: "asceno", file: "characters/asceno.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  jepanya: { key: "jepanya", file: "characters/jepanya.png", frameWidth: FW, frameHeight: FH, frameCount: 6, anims: npcAnims() },
};

export const ALL_SPRITES: CharSprite[] = Object.values(SPRITES);

export const PLAYER_KEY = "siggy";

/** Full Phaser animation key for a character + anim name. */
export function animKey(charKey: string, name: string): string {
  return `${charKey}-${name}`;
}

/** Portrait PNG path (transparent) for the dialog UI. */
export function portraitPath(charKey: string): string {
  return `/characters/portraits/${charKey}.png`;
}
