// Per-character spritesheet + animation configuration.
//
// All processed strips are uniform 220x220 horizontal frames generated by
// scripts/preprocess-sprites.cjs from the magenta reference sheets. Frame counts
// come from that script's output. The source art is a set of varied poses (not
// directional walk cycles), so directional movement is handled in the scene by
// horizontally flipping the sprite; the animations below cycle the available
// poses to keep characters lively.

export interface AnimDef {
  /** suffix; full key becomes `${charKey}-${name}` */
  name: string;
  frames: number[];
  frameRate: number;
  repeat: number; // -1 = loop
}

export interface CharSprite {
  key: string;
  file: string; // under /public
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  anims: AnimDef[];
}

const FW = 220;
const FH = 220;

// The source art is a set of varied poses (different sizes/positions within
// each 220px frame), so cycling frames makes a character appear to grow/shrink.
// We therefore keep every character on a single consistent frame and convey
// life through movement (player bob, NPC wander) instead of frame swaps.
function npcAnims(): AnimDef[] {
  return [{ name: "idle", frames: [0], frameRate: 1, repeat: -1 }];
}

export const SPRITES: Record<string, CharSprite> = {
  // Player. 6 poses: 0 sit/idle, 1-2 step, 3 dash, 4 sit-alt, 5 pounce.
  siggy: {
    key: "siggy",
    file: "characters/siggy.png",
    frameWidth: FW,
    frameHeight: FH,
    frameCount: 6,
    anims: [
      // SiggyRevamp sheet: 0/1 left-facing, 2 back, 3 front-sit, 4/5 front
      // upright. Frames 4 & 5 are both front upright of equal size -> clean
      // walk; 3 & 5 (front) make a calm idle without size jitter.
      { name: "idle", frames: [5, 3], frameRate: 1.6, repeat: -1 },
      { name: "walk", frames: [4, 5], frameRate: 8, repeat: -1 },
      { name: "run", frames: [4, 5], frameRate: 13, repeat: -1 },
      { name: "interact", frames: [3], frameRate: 6, repeat: 0 },
      { name: "celebrate", frames: [4, 5], frameRate: 8, repeat: 3 },
      { name: "sit", frames: [3], frameRate: 1, repeat: 0 },
    ],
  },
  seesac: { key: "seesac", file: "characters/seesac.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  siggy_anime: { key: "siggy_anime", file: "characters/siggy_anime.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  decka: { key: "decka", file: "characters/decka.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  // nxr_new is a clean 6-pose walk cycle; a light 2-frame "jog" reads as training.
  nxr: {
    key: "nxr",
    file: "characters/nxr.png",
    frameWidth: FW,
    frameHeight: FH,
    frameCount: 6,
    anims: [
      { name: "idle", frames: [2, 3], frameRate: 3.5, repeat: -1 },
      { name: "walk", frames: [2, 3, 5], frameRate: 8, repeat: -1 },
    ],
  },
  rikky: { key: "rikky", file: "characters/rikky.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  rizan: { key: "rizan", file: "characters/rizan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  jez: { key: "jez", file: "characters/jez.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  stefan: { key: "stefan", file: "characters/stefan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  josh: { key: "josh", file: "characters/josh.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  evo: { key: "evo", file: "characters/evo.png", frameWidth: FW, frameHeight: FH, frameCount: 6, anims: npcAnims() },
  asceno: { key: "asceno", file: "characters/asceno.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  jepanya: { key: "jepanya", file: "characters/jepanya.png", frameWidth: FW, frameHeight: FH, frameCount: 6, anims: npcAnims() },
  mexxy: { key: "mexxy", file: "characters/mexxy.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  tutubear: { key: "tutubear", file: "characters/tutubear.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  john: { key: "john", file: "characters/john.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  yourinuu: { key: "yourinuu", file: "characters/yourinuu.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  linhlambo: { key: "linhlambo", file: "characters/linhlambo.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  agata: { key: "agata", file: "characters/agata.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  whuan: { key: "whuan", file: "characters/whuan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  kippo: { key: "kippo", file: "characters/kippo.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  hytamm: { key: "hytamm", file: "characters/hytamm.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  shin: { key: "shin", file: "characters/shin.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },

  // --- new roster ---
  habex: { key: "habex", file: "characters/habex.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  moctx: { key: "moctx", file: "characters/moctx.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  absol: { key: "absol", file: "characters/absol.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  bien: { key: "bien", file: "characters/bien.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  babass: { key: "babass", file: "characters/babass.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  chala: { key: "chala", file: "characters/chala.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  flylucifer: { key: "flylucifer", file: "characters/flylucifer.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  kaidanzer: { key: "kaidanzer", file: "characters/kaidanzer.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  kamalz: { key: "kamalz", file: "characters/kamalz.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  ng: { key: "ng", file: "characters/ng.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  omartuta: { key: "omartuta", file: "characters/omartuta.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  online: { key: "online", file: "characters/online.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  rz: { key: "rz", file: "characters/rz.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  skyzee: { key: "skyzee", file: "characters/skyzee.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  stanelope: { key: "stanelope", file: "characters/stanelope.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  starknight: { key: "starknight", file: "characters/starknight.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  subur: { key: "subur", file: "characters/subur.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  travis: { key: "travis", file: "characters/travis.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },

  // --- newest roster ---
  baster: { key: "baster", file: "characters/baster.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  hazelnty: { key: "hazelnty", file: "characters/hazelnty.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  tutufly: { key: "tutufly", file: "characters/tutufly.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  sayangxbt: { key: "sayangxbt", file: "characters/sayangxbt.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  shen: { key: "shen", file: "characters/shen.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  strobely: { key: "strobely", file: "characters/strobely.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  deell: { key: "deell", file: "characters/deell.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },

  // --- newest requested roster ---
  baemax: { key: "baemax", file: "characters/baemax.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  billiebed: { key: "billiebed", file: "characters/billiebed.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  batagor: { key: "batagor", file: "characters/batagor.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  icebear: { key: "icebear", file: "characters/icebear.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  dikzzy: { key: "dikzzy", file: "characters/dikzzy.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  nadsar: { key: "nadsar", file: "characters/nadsar.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  skylaaark: { key: "skylaaark", file: "characters/skylaaark.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  oyeng: { key: "oyeng", file: "characters/oyeng.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  juggernaut: { key: "juggernaut", file: "characters/juggernaut.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  keybi: { key: "keybi", file: "characters/keybi.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  callmehann: { key: "callmehann", file: "characters/callmehann.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },

  // --- extra community roster ---
  kai: { key: "kai", file: "characters/kai.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  qaziharis: { key: "qaziharis", file: "characters/qaziharis.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  cici: { key: "cici", file: "characters/cici.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  babysyen: { key: "babysyen", file: "characters/babysyen.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  oxshee: { key: "oxshee", file: "characters/oxshee.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  chocothins: { key: "chocothins", file: "characters/chocothins.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  yetece: { key: "yetece", file: "characters/yetece.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  furiju: { key: "furiju", file: "characters/furiju.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  firless: { key: "firless", file: "characters/firless.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
  cheastersaz: { key: "cheastersaz", file: "characters/cheastersaz.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims() },
};

export const ALL_SPRITES: CharSprite[] = Object.values(SPRITES);

export const PLAYER_KEY = "siggy";

const PLAYER_LABELS: Record<string, string> = {
  siggy: "Siggy Black Cat",
  siggy_anime: "Siggy Anime Girl",
  nxr: "NXR",
  rz: "RZ",
  ng: "NG",
  baemax: "Baemax",
  billiebed: "Billiebed",
  batagor: "Batagor",
  icebear: "Icebear",
  dikzzy: "Dikzzy",
  nadsar: "Nadsar",
  skylaaark: "Skylaaark",
  oyeng: "Oyeng",
  juggernaut: "Juggernaut",
  keybi: "Keybi",
  callmehann: "Callmehann",
  kai: "Kai",
  qaziharis: "QaziHaris",
  cici: "Cici",
  babysyen: "BabySyen",
  oxshee: "OxShee",
  chocothins: "ChocoThins",
  yetece: "Yetece",
  furiju: "FuriJu",
  firless: "Firless",
  cheastersaz: "CheasterSaz",
};

function labelFromKey(key: string): string {
  return PLAYER_LABELS[key] ?? key.split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ");
}

export const PLAYABLE_CHARACTERS = ALL_SPRITES.map((sprite) => ({
  key: sprite.key,
  label: labelFromKey(sprite.key),
}));

/** Full Phaser animation key for a character + anim name. */
export function animKey(charKey: string, name: string): string {
  return `${charKey}-${name}`;
}

/** Portrait PNG path (transparent) for the dialog UI. */
export function portraitPath(charKey: string): string {
  return `/characters/portraits/${charKey}.png`;
}
