// Per-character spritesheet + animation configuration.
//
// All processed strips are uniform 220x220 horizontal frames generated by
// scripts/preprocess-sprites.cjs from the magenta reference sheets. Frame counts
// come from that script's output. The source art is a set of varied poses (not
// directional walk cycles), so directional movement is handled in the scene by
// horizontally flipping the sprite; the animations below cycle the available
// poses to keep characters lively.

export interface AnimDef {
  /** suffix; full key becomes `${charKey}-${name}` */
  name: string;
  frames: number[];
  frameRate: number;
  repeat: number; // -1 = loop
}

export interface CharSprite {
  key: string;
  file: string; // under /public
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  anims: AnimDef[];
}

const FW = 220;
const FH = 220;

// Standard idle/talk cycle for a 4-frame NPC strip.
function npcAnims(frameCount: number): AnimDef[] {
  const f = (i: number) => Math.min(i, frameCount - 1);
  return [
    { name: "idle", frames: [f(0), f(1), f(0), f(2)], frameRate: 3, repeat: -1 },
    { name: "talk", frames: [f(0), f(1), f(2), f(3)], frameRate: 6, repeat: -1 },
  ];
}

export const SPRITES: Record<string, CharSprite> = {
  // Player. 6 poses: 0 sit/idle, 1-2 step, 3 dash, 4 sit-alt, 5 pounce.
  siggy: {
    key: "siggy",
    file: "characters/siggy.png",
    frameWidth: FW,
    frameHeight: FH,
    frameCount: 6,
    anims: [
      // single idle frame so the cat doesn't appear to change size between poses
      { name: "idle", frames: [0], frameRate: 1, repeat: -1 },
      { name: "walk", frames: [1, 2, 3], frameRate: 8, repeat: -1 },
      { name: "run", frames: [1, 2, 3], frameRate: 13, repeat: -1 },
      { name: "interact", frames: [5], frameRate: 6, repeat: 0 },
      { name: "celebrate", frames: [4, 5], frameRate: 6, repeat: 3 },
      { name: "sit", frames: [0], frameRate: 1, repeat: 0 },
    ],
  },
  seesac: { key: "seesac", file: "characters/seesac.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  siggy_anime: { key: "siggy_anime", file: "characters/siggy_anime.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  decka: { key: "decka", file: "characters/decka.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  nxr: { key: "nxr", file: "characters/nxr.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  rikky: { key: "rikky", file: "characters/rikky.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  rizan: { key: "rizan", file: "characters/rizan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  jez: { key: "jez", file: "characters/jez.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  stefan: { key: "stefan", file: "characters/stefan.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
  josh: { key: "josh", file: "characters/josh.png", frameWidth: FW, frameHeight: FH, frameCount: 4, anims: npcAnims(4) },
};

export const ALL_SPRITES: CharSprite[] = Object.values(SPRITES);

export const PLAYER_KEY = "siggy";

/** Full Phaser animation key for a character + anim name. */
export function animKey(charKey: string, name: string): string {
  return `${charKey}-${name}`;
}

/** Portrait PNG path (transparent) for the dialog UI. */
export function portraitPath(charKey: string): string {
  return `/characters/portraits/${charKey}.png`;
}
